### ISSUE TITLE
the whole step question

### ISSUE THREAD

**Issue by NobelNelson** [dsnslab/NetworkSecurity#17]
可以請問助教整個步驟是如何進行的嗎?
![image](https://user-images.githubusercontent.com/72659729/96456929-c0217080-1251-11eb-8b36-14cdaa92c8e3.png)
第一個步驟下載完our docker files後已經是包含了甚麼文件?
我看裡面有docker-compose.yml 、 internal-use.yml 、logstash.yml 、logstash.conf
(1)而裡面這個docker-compose跟從網路上載下來的有什麼不一樣?
(2)哪ELK Stack又去哪裡了?Elasticsearch是包含docker-compose.yml internal-use.yml 就是Elasticsearch ?Logstash裡面有了就是logstash.yml 、logstash.conf，需要設定什麼開啟甚麼嗎? Kibana是Winlogbeat、Packetbeat嗎?
(3)sudo docker compose up跑完已經是跑了Elasticsearch、Logstash嗎?最後一步驟聯網才是開啟Kibana跑Kibana嗎?
(4)跑Elasticsearch、Logstash是在虛擬機上跑，所以只有Kibana需要處理port問題，也就是5601、5044?如果不是的話這還有少甚麼?
![image](https://user-images.githubusercontent.com/72659729/96459026-30c98c80-1254-11eb-83a7-cb5e9aeb5bda.png)
(5) VMnet1為主機ip，enp0s為客機ip?
(6)前面問題說要確認能不能連在windows上打ping 10.0.2.15，不過我的顯示這樣是沒有連到?
![image](https://user-images.githubusercontent.com/72659729/96459619-e5fc4480-1254-11eb-80cb-37681d55cd39.png)

**Comment by NobelNelson** [comment]
還有阿Winlogbeat、Packetbeat又是什麼東西啊?
Winlogbeat、Packetbeat要怎麼裝也不講，拆開來放這就好，不用啟動什麼東西?

**Comment by NobelNelson** [comment]
整個步驟就四個動作，又沒有提到Winlogbeat，Packetbeat什麼時候開，什麼時候用?
可以請助教講清楚該如何使用這些東西嗎?

**Comment by NobelNelson** [comment]
![image](https://user-images.githubusercontent.com/72659729/96473279-08498e80-1264-11eb-9532-9b9b8687b69b.png)
我看我的docker裡是這樣
這樣有把需要的port都接上去?

**Comment by dsnslab** [comment]
同學你好，
就像我們在spec中提到的，我們提供的docker file中包含了整個ELK stack，也就是Elasticsearch、Logstash以及Kibana。
1. 我們提供的docker-compose.yml是使我們的docker file中的node們能夠以正確的方式運作，也就是以投影片中提到的ELK stack的架構運作。
2. ELK stack就如前面、投影片、spec中所述，就是我們docker file中所包含的東西們，也就是Elasticsearch、Logstash以及Kibana。logstash的config並不需要去多做額外的設定。 
Kibana並不是winlogbeat, packetbeat，並且這三者的角色及功能在投影片、投影片報告以及spec中已提及囉，如何安裝beat於官方頁面上也講解的十分清楚，安裝及使用beats為此次作業的內容，因此並不直接給予指令。
3. sudo docker-compose up之後，ELK的三個部份都跑起來囉。Kibana已經docker file中開啟囉，瀏覽器只是顯示kibana的工具。
4. Logstash需要處理port forwarding的問題，Kibana則需看你想用什麼方式開啟以決定是否需要處理。
5. 希望同學你可以再詳加敘述一下第5個問題，我沒有很了解你的問題。
6. VirtualBox需要處理port forwarding，。前面的同學已解決的issue中也有提及更詳細的資訊，能夠上網自行了解整個概念，也可以直接參考issue。

**Comment by afcidk** [comment]
Please be polite and gentle when asking questions, being so offensive won't make your situation better 😃 
I'm also the student in this class. Maybe I could answer some of your questions though.

Q1: What is the difference between the provided docker-compose and the one on the Internet?
A1: I think the provided `elastic.zip` contains some settings that should let you set up the ELK stack easier if you follow those four instructions step-by-step. However, that's just the suggested way but **not** the only way to setup. There are many tutorials[[1]](https://www.elastic.co/what-is/elk-stack) on the Internet (even in Chinese[[2]](https://ithelp.ithome.com.tw/articles/10200989)[[3]](https://snoopy30485.github.io/2018/07/26/ELK%E4%BB%8B%E7%B4%B9/)!) for you to follow, and I think it makes no difference whether you setup by yourself or use TA's.

Q2: Then where is the ELK Stack? Elasticsearch contains `docker-compose.yml`, and `internal-user.yml` is Elasticsearch? (Sorry, but I cannot fully understand what you mean) We have `logstash.yml` and `logstash.conf`, do we need to setup or enable something? Is Kibana Winlogbeat or Packetbeat?
A2: You put too many question in one single question, so my answer might be a little bit hard to read 👶 . First, you could setup the ELK stack after you follow the four instructions step-by-step as I mentioned in Q1. So... yeah, ELK stack is right there after you run the instructions. I cannot understand what you mean in the second question. Try to review what you've written and ensure that you have appropriate grammar and punctuation marks so that others could help you with your problem :-). Second, we don't need to do further edits to those files. Just as I said previously (and if you listened carefully in class, TAs should have said as well. At least I've heard that), this is a faster way to setup ELK stack for you if you run the instructions step-by-step. Third, Kibana is neither Winlogbeat nor Packetbeat. As mentioned in the slide (p4), beats[[4]](https://www.elastic.co/beats/) is the data shippers and Kibana[[5]]() is part of ELK stack (which is used for data visualization). 

Q3: Does that mean I've runned Elasticsearch and Logstash after `sudo docker compose up`? Is the last step (connect to Kibana using browser) the step to run Kibana?
A3: Actually, it's `sudo docker-compose up`. For the question, you have to wait for some time after running `sudo docker-compose up`. But yes, you have runned Elasticsearch and Logstash and Kibana after running that command. One thing you need to notice is that some nodes might fail to start if you did not run the second instruction (increase the virtual memory limit). The command won't exit, so you have to pay extra attention on it to see if it failed or not :-).

I'll leave Q4 to Q6 to others.

> 還有阿Winlogbeat、Packetbeat又是什麼東西啊?
> Winlogbeat、Packetbeat要怎麼裝也不講，拆開來放這就好，不用啟動什麼東西?

For this question, I suggest you take a look at the official document. We have two weeks to do this homework, and I think these articles are not really hard to read(?). Since there is only one day left before the deadline of this homework, I will try to summarize these two applications in three lines.
Beat means shippers, you pass the data to ELK stack via beats.
Winlogbeat passes windows log.
Packetbeat passes packets.
![image](https://user-images.githubusercontent.com/21095621/96482809-7e52f300-126e-11eb-90e0-45df641b8bf6.png)

> 整個步驟就四個動作，又沒有提到Winlogbeat，Packetbeat什麼時候開，什麼時候用?
> 可以請助教講清楚該如何使用這些東西嗎?

The four instructions does not include setting up Winlogbeat and Packetbeat. Those instructions are for ELK stack(p.9, p.10), but beats should installed on your Windows(p.11). Does it make sense to you?

[1] ELK Stack: What is the ELK Stack? https://www.elastic.co/what-is/elk-stack
[2] Day 11 ELK 收集系統Log https://ithelp.ithome.com.tw/articles/10200989
[3] ELK介紹 https://snoopy30485.github.io/2018/07/26/ELK%E4%BB%8B%E7%B4%B9/
[4] Beats: Lightweight data shippers https://www.elastic.co/beats/
[5] Kibana: Your window into the Elastic Stack https://www.elastic.co/kibana

Correct me if I'm wrong, thanks!
