### ISSUE TITLE
Is the Log file has correct format?

### ISSUE THREAD

**Issue by che30122** [dsnslab/NetworkSecurity#24]
Scenario:
when I try to use "elasticdump" to import log data to my elastic search,I got an error.
error log like below:
{
  _index: 'my_index',
  _type: '_doc',
  _id: '4mwlHnYBWeK1m2KP0ZrY',
  status: 400,
  error: {
    type: 'mapper_parsing_exception',
    reason: 'failed to parse',
    caused_by: {
      type: 'not_x_content_exception',
      reason: 'Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes'
    }
  }
}

**Comment by SnowWhite1129** [comment]
Maybe you can try [this](https://stackoverflow.com/questions/35213472/elasticsearch-error-while-sending-data/48687954).
Try to google error message, and you will get proper answer.
`google "Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes"`

**Comment by lilychou0105** [comment]
Hi, I have the same problem as above, however, I not sure about the solution. According to the link provided and I also google about it, it seems that the problem is about the json file format? However, I don't think the json files TA provided will need to be modified. Moreover, most of the question are like [https://github.com/elastic/elasticsearch-rails/issues/606](url) which I consider it hard to find the relation between this and the project. Please help, I already stuck here the whole afternoon QQ
![image](https://user-images.githubusercontent.com/72923437/101140140-82d04100-364d-11eb-9ebc-b40ac09d431e.png)
This is my command for sending json files to elasticsearch.
*I can get data from ELK to json file, but can't sent raw json file to ELK

**Comment by afcidk** [comment]
Here's an easier approach to visualize your data.

Use the [official ElasticSearch service](https://www.elastic.co/cloud/elasticsearch-service/signup) (14-day trial).
In the service, you can simply upload the JSON file and visualize them easily. You can follow this [video](https://morioh.com/p/ad90e8b4f04e) to see how to upload logs to the service.

Note that this is just a workaround if you don't want to spend too much time figuring how to use elasticdump 🐤 .

**Comment by lilychou0105** [comment]
@afcidk WOW! This is really helpful. Thanks a lot!!

**Comment by chiha8888** [comment]
Thanks @afcidk !   
But after import json file to Kibana,it can't show up in Kibana/Discover.  
Did I have to edit the grok pattern in the importing json file step?  

It successfully imported.  
![png](https://i.imgur.com/qACnHRn.png)  

Can't show up in Discover.  
![png](https://i.imgur.com/PrZ3vdg.png)

Does anyone face about this problem?

**Comment by lilychou0105** [comment]
@chiha8888 the time on right-top should be set like 2 months ago

**Comment by rreexxllii0310** [comment]
How to upload the file packetbeat.json in  folder Attack_1 to data visualizer with exceeding 100 MB size?
I can't upload it.
