### ISSUE TITLE
Stuck in pj2

### ISSUE THREAD

**Issue by VaTanJo** [dsnslab/NetworkSecurity#30]
Can classmates or TAs give me some suggestions or tips for project2?
I think I am in trouble T^T

Currently I have tried to import log into elasticsearch by using elasticdump
But I have no idea how to visualize and analyze in KIBANA

And I didn’t have any machine learning experience before
A little difficult for me
There are too many packages, but I don’t know which one is suitable for this job
(multi-class classification?)

So I came up to ask for help, hoping someone could give me directions to complete the assignment  QQ

Thanks

**Comment by afcidk** [comment]
You can start from looking at the closed issues first.
The answers in #24 should help you visualize the logs. 🐈

**Comment by jehoshuapratama** [comment]
First of all, 
you need to analyze the logs. It is easier to do it using Kibana. You could use the import feature if you have difficulties using elasticdump mentioned in closed issues.
Or you could do it manually, by opening the file using excel and analyze them 1 by 1. (Not recommended since it will take a lot of your time).

Next, 
if you use rule based: you need to see what pattern is it involving in the log for each attack. Then categorize those pattern into 5 attacks (since we have 5 attacks)
if you use Machine Learning: probably you need to sort which feature will be used for all the attack and give labels.

Lastly,
Used the informations you gain from last step to evaluate the performance using the Example Test.

This is my guideline on doing this project. It might be different to others but if you like to follow my suggestion go ahead.

**Comment by VaTanJo** [comment]
Thanks you! 
After a whole day of trying, the logs can be analyzed smoothly!!! <3
Although I haven't started machine learning yet
