### ISSUE TITLE
setting group policy editor

### ISSUE THREAD

**Issue by jack25946705** [dsnslab/NetworkSecurity#43]
請問要如何正確設定這次作業的group policy editor?
我感覺是在user configuration->windows settings->scripts(logon/logoff)裡輸入想要觀察的指令(新增刪除檔案 開啟關閉小算盤)
但是我仍在在event viewer與kibana上沒看到相關log

**Comment by dsnslab** [comment]
The reason why we only introduce you group policy editor in the slide but not the configuration of it is because **this is part of the homework**.

We're sorry to say that we could not directly tell you how to configure it. You have to search the Internet for the answer.
Take the `calc.exe` scenario for example, maybe you can try the following keyword on google and find the necessary information you need:

```
group policy editor enable process audit
```
